const Map<String, String> enUS = {
  "not_specified": "",
  "unauthenticated": "Unauthenticated",
  "sample_text": "This is an example text that can be replaced in the same space. This text has been generated from an Arabic text generator, where you can generate such text or many other texts.",
  "app_name": "First Responder",
  "no_internet_connection": "No internet connection",
  "required": "Required",
  'user_name': 'Username',
  'enter_your_user_name': 'Enter your user name here',
  'enter_valid_user_name': 'Enter Valid user name',
  'password': 'Password',
  'enter_your_password': 'Enter your password',
  'enter_valid_password': 'Enter valid password',
  'remember_me': 'Remember me',
  'save_user_name_for_next': 'Save your user name for next time',
  'next': 'Next',
  'step_1': 'Step 1 of 2: Sign In',
  'arabic':'العربية',
  'invalid_link':'Please enter a valid domain name',
  'url_required':'Url Server is required',
  'admin_settings':'Admin Settings',
  'configure_server_url':'Configure Server URL',
  'http_ex':'https://example.com',
  'cancel_edit':'Cancel edit',
  'edit':'Edit',
  'cancel':'Cancel',
  'save':'Save',
  'welcome':'Welcome,',
  'step_2':'Step 2 of 2: Select Your Unit',
  'recently_logged_units':'Recently Logged Units',
  'no_recently_units':'No recently logged units',
  'or':'OR',
  'unit_id':'Unit Id',
  'select_your_unit':'Select your unit',
  'back':'Back',
  'login':'Log In',
  'current_location':'Current Location',
  'unit_details':'Unit Details',
  'shift_log':'Shift Log',
  'filed_event':'Filed Event',
  'update_unit_state':'Update Unit State',
  'other_status_options':'Other status options',
  'additional_status':'Additional status',
  'confirm_status_chane':'Confirm status change',
  'you_are_about_change_status':'You are about to change your unit staus from:',
  'current':'Current',
  'new':'New',
  'confirm':'Confirm',
  // drawer **********************************************
  'my_unit':'My Unit',
  'my_unit_body':'Status overview and history',
  'inquiry':'Inquiry',
  'inquiry_body':'Search incidents and records',
  'broadcasts':'Broadcasts',
  'broadcasts_body':'Department-wide alerts',
  'messages':'Messages',
  'messages_body':'View and send secure messages',
  'settings':'Settings',
  'settings_body':'App preferences and configuration',
  'help':'Help',
  'help_body':'Support and documentation',
  'app_version':'App version',
  'build':'Build',
  'map_layers':'Map Layers',
  'base_map':'Base Map',
  'layers':'Layers',
  'nearby':'Nearby',
  // Notification **********************************************
  'notifications':'Notifications',
  'mark_all_read':'Mark all read',
  'coming_soon':'Coming Soon',
  // Profile & Unit **********************************************
  'officer':'Officer',
  'my_shift_history':'My Shift History',
  'view_past_shifts':'View past shift and reports',
  'my_assigned_unit':'My Assigned Unit',
  'theme':'Theme',
  'dark':'Dark',
  'light':'Light',
  'logout':'Log Out',
  'end_session_and_return_to_login':'End session and return to login',
  'confirm_logout':'Confirm Logout',
  'confirm_logout_body':'Are you sure you want to log out? Your session will end and your unit will be unassigned.',
  'shift_history':'Shift History',
  'status':'Status',
  'zone':'Zone',
  'officer_information':'Officer Information',
  'name':'Name',
  'badge':'Badge',
  'shift_start':'Shift start',
  'shift_en':'Shift end',
  'vehicle_details':'Vehicle Details',
  'vehicle_id':'Vehicle id',
  'license_plate':'License plate',
  'fuel_level':'Fuel level',
  'mileage':'Mileage',
  'last_maintenance':'Last maintenance',
  'cleared_events':'Cleared Events',
  'preempted_events':'Preempted Events',
  'in_progress':'In progress',
  'today':'Today',
  'last_5_events':'Last 5 Events',
  'this_week':'This Week',
  // Settings **********************************************
  'general':'General',
  'language_and_preference_settings':'Language and preference settings',
  'map_navigation':'Map & Navigation',
  'map_preference_layers_and':'Map preference, layers, and Units',
  'emergency':'Emergency',
  'critical_safety_and_emergency':'Critical safety and emergency',
  'configure_your_preference':'Configure your preferences',
  'select_setting_section':'Select a Settings Section',
  'choose_section_from_side_bar':'Choose a section from the sidebar to configure your preferences',
  'app_language':'App Language',
  'choose_your_default_app_language':'Choose your default app language',
  'english':'English',
  'app_theme':'App Theme',
  'choose_between_light_dark':'Choose between light and dark appearance',
  'all_preference_are_saved':'All preferences are saved automatically when changed',
  'map_preference':'Map Preferences',
  'configure_default_map_behavior':'Configure default map behavior and view settings',
  'default_map_view':'Default Map View',
  'choose_what_you_see_when_you_first_open_map':'Choose what you see when you first open the map',
  'long_press_with_two_finger_ta_active_sos':'Long press with two fingers to activate SOS',
  'tow_finger_emergency_gesture':'Two-Finger Emergency Gesture',
  'critical_safety_feature_for_urgent_distress':'Critical safety feature for urgent distress situations',
  'emergency_gesture':'Emergency Gesture',
  'display_unit_name':'Display unit names on the map',
  'choose_which_map_types_loads':'Choose which map type loads first when you open the map',
  'default_base_view':'Default Base Map',
  'configure_default_map_layer':'Configure default map layers and base map style',
  'configure_your_preferences':'Configure your preferences',
  'configure_server_connection':'Configure Server Connection',
  'configure_server_connection_sub_title': "Enter your organization's secure server address to begin \n setup.",
  'server_url':'Server Url',
  'connect':'Connect',
  // Unit in danger **********************************************
  'active_unit_in_danger':'Activating Unit in Danger...',
  'unit_danger_desc':'This will notify the Control Room and all nearby units with your location and event details.',
  'undo':'UNDO',
  'extend_delay_ensure_intentional_activation':'Extended delay ensures intentional activation',
  'sending_in':'Sending in',
  'seconds...':'seconds...',
  'unit_in_danger':'UNIT IN DANGER',
  'sent_at':'Sent at:',
  'cancel_sos':'Cancel Sos',
  'confirm_cancellation':'Confirm Cancellation',
  'to_cancel_unit_in_danger_state':'To cancel the Unit in Danger state, enter your security code.',
  // Basics *********************************************************************
  'server_error':'Server Error, try again later...',
  'wrong_url':'The Server URL you entered is not correct',
  'getting_server_data':'Getting server data',
  'you_must_select_unit':'You should select unit to login with',
  'enter_server_url':'Enter server url',
  'verifying_connection':'Verifying connection..',
  'sign_in':'Sign in',
  'loading':'Loading..',
  'lost_connection':'Offline – Lost connection to server',
  '':'',
};
