name: responder_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Ui ##########################################################################
  cupertino_icons: ^1.0.8
  flash: ^3.1.1
  flutter_svg: ^2.0.17
  flutter_spinkit: ^5.2.1
  skeleton_loader: ^2.0.0+4
  photo_view: ^0.15.0
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.2.1
  lottie: ^3.1.2
  permission_handler: ^12.0.0+1
  percent_indicator: ^4.2.5
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  package_info_plus: ^8.3.0

  # GetX ###########################################################################################
  get: ^4.7.2
  get_storage: ^2.1.1

  #  Google Services ###############################################################################
  google_maps_flutter: ^2.12.3

  # GPS Services ###################################################################################
  location: ^5.0.0

  #  Network #######################################################################################
  pretty_dio_logger: ^1.4.0
  network_logger: ^1.0.4



  dio: any
  path: any
  intl: any
  rxdart: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/json/
    - assets/images/
    - assets/animations/
    - assets/flags/
#    - assets/tiles/



  fonts:
    - family: BOLD
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/Tajawal-Medium.ttf
    - family: Regular
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

